[workspace]
name = "threshold_elgamal_fe_reference"
version = "0.1.0"
members = { main = ["ingots/threshold_elgamal_fe"], dev = ["ingots/threshold_elgamal_fe_tests"] }
default-members = ["ingots/threshold_elgamal_fe"]
